name = "directlink"
main = "src/index.js"
compatibility_date = "2024-01-29"
workers_dev = false

[[kv_namespaces]]
binding = "KV"
id = "66f231d4d11641d0bac63cfe45d837d8"

[[routes]]
pattern = "api.syshub.top/directlink/*"
zone_name = "syshub.top"

[vars]
PATH_PREFIX = "/directlink"
_123 = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDc0NzQwMzksImlhdCI6MTcwNjg2OTIzOSwiaWQiOjE4MTcwNjY3MjEsIm1haWwiOiIiLCJuaWNrbmFtZSI6IjE5NzIxNjEwMTY4Iiwic3VwcGVyIjpmYWxzZSwidXNlcm5hbWUiOjE5NzIxNjEwMTY4LCJ2IjowfQ.XQmtcXywRaF36whHZus1M3-d0FPyO4ZRV6O9lXCNmWM"
_189 = "2701E13DA0EA05A5783569F90BCEE9B3DF0E3E97E2FB36C45C8591A1F1B600EC92F50AE36DCBD86EB364C3840AE2D270"